### ISSUE TITLE
Port and URI in README

### ISSUE THREAD

**Issue by BlackRose01** [arrowhead-f/mgmt-tool-js#2]
Could you please describe the port and uri in the README after the mgmt-tool successfully starts because the server didn't run on the standard web ports.

**Comment by tsvetlin** [comment]
Hello! In the docker you can specify the port on what you would like to run it
-p outside_port:internal_port
if you want to run it on another port, you should change the outside_port to your desired port.

docker run -it --rm -p 3000:5000 
--name arrowhead-react-container 
-e REACT_APP_ARROWHEAD_SR_URL=http://arrowhead.tmit.bme.hu:8342 
-e REACT_APP_ARROWHEAD_ORCH_URL=http://arrowhead.tmit.bme.hu:8340 
-e REACT_APP_ARROWHEAD_GK_URL=http://arrowhead.tmit.bme.hu:8348 
svetlint/arrowhead-react

**Comment by BlackRose01** [comment]
thank you for the answer
