### ISSUE TITLE
Unable to understand issue with management tool

### ISSUE THREAD

**Issue by sumi0910** [arrowhead-f/mgmt-tool-js#3]
![image](https://user-images.githubusercontent.com/44111991/67403085-c08d1a00-f5b1-11e9-99d0-d6ad4c2f5cc9.png)

taking more than needed time (15 min)

**Comment by tsvetlin** [comment]
Hello!

Your VM is probably weak. 
The new version of the mgmt-tool will have a faster startup time. (It's still in development)

Best wishes,
Svetlin

**Comment by sumi0910** [comment]
I am using the following command 
sudo docker run -it --rm -p 9000:5000 --name arrowhead-react-container -e REACT_APP_ARROWHEAD_SR_URL=http://192.168.237.131:8442 -e REACT_APP_ARROWHEAD_ORCH_URL=http://192.168.237.131:8440 -e REACT_APP_ARROWHEAD_GK_URL=http://192.168.237.131:8448 svetlint/arrowhead-react 
and i am getting error with respect to xsel binary now though I have increased the RAM size and did installed xsel. Attached image will give you brief detail about the issue. 

![image](https://user-images.githubusercontent.com/44111991/67467316-d568bc80-f648-11e9-8f81-f400610aaee4.png)

**Comment by sumi0910** [comment]
solved

**Comment by EricChiquitoG** [comment]
Hi, how did you solved it? Having the same issue

**Comment by tsvetlin** [comment]
Hello! 
What is your server/VM configuration?
