### ISSUE TITLE
Hardcoded URL's in docker version?

### ISSUE THREAD

**Issue by XsylenZ** [arrowhead-f/mgmt-tool-js#4]
Hi,

I know you guys are working hard on a new release, but would it be possible to update the docker version with a version that doesn't have the URL hard coded in there? 

As you can see on the picture below, it's directing to the public server. The rest of the tool is working just fine, but right now I still need to enter all the authorisation rules through swagger.

![image](https://user-images.githubusercontent.com/10152270/68075184-9f43df00-fda4-11e9-9e21-5f3d33766171.png)

**Comment by tsvetlin** [comment]
Hello!

There are NO hardcoded URL-s. Not in the Docker version nor in the compiled version. The URL-s are defined in environmental variables. 

How did you run it?

**Comment by XsylenZ** [comment]
Okay,

Maybe I missed something during the startup  then.

What I used to start the docker version is:

docker run -it --rm -p 3000:5000 --name arrowhead-react-container \
-e REACT_APP_ARROWHEAD_SR_URL=http://deb-arrowhead.local:8442 <http://deb-arrowhead.local:8442/> \
-e REACT_APP_ARROWHEAD_ORCH_URL=http://deb-arrowhead.local:8440 <http://deb-arrowhead.local:8440/> \
-e REACT_APP_ARROWHEAD_GK_URL=http://deb-arrowhead.local:8448 <http://deb-arrowhead.local:8448/> \
-e REACT_APP_ARROWHEAD_AUTH_URL=http://deb-arrowhead.local:8444 <http://deb-arrowhead.local:8444/> \
-e REACT_APP_ARROWHEAD_EH_URL=http://deb-arrowhead.local:8454 <http://deb-arrowhead.local:8454/> \
-e REACT_APP_ARROWHEAD_CHOREOGRAPHER_URL=http://deb-arrowhead.local:8456 <http://deb-arrowhead.local:8456/> \
svetlint/arrowhead-react

But still it will try to find the intracloud information from a different location as you can see here:

![image](https://user-images.githubusercontent.com/10152270/68077805-90702300-fdca-11e9-9c42-436866ebd9ce.png)

**Comment by tsvetlin** [comment]
You know that the Management Tool is not yet updated to support 4.1.3, right?
Why do you have another url inside <>? It can't be right...

**Comment by XsylenZ** [comment]
Yes I know, that's why I use 4.1.2 ;) (it's for my internship, so can't be bothered with secure mode at the moment and internship ends at 31 of january) 

They command as show in my last reply should look like this, I did send my reply from mail so got messed up:

docker run -it --rm -p 3000:5000 --name arrowhead-react-container \
-e REACT_APP_ARROWHEAD_SR_URL=http://deb-arrowhead.local:8442 \
-e REACT_APP_ARROWHEAD_ORCH_URL=http://deb-arrowhead.local:8440 \
-e REACT_APP_ARROWHEAD_GK_URL=http://deb-arrowhead.local:8448 \
-e REACT_APP_ARROWHEAD_AUTH_URL=http://deb-arrowhead.local:8444 \
-e REACT_APP_ARROWHEAD_EH_URL=http://deb-arrowhead.local:8454 \
-e REACT_APP_ARROWHEAD_CHOREOGRAPHER_URL=http://deb-arrowhead.local:8456 \
svetlint/arrowhead-react

**Comment by tsvetlin** [comment]
It looks fine. But there are no hardcoded url values in the code, everything comes from environmental variables. Haven't you started up the Management Tool first with the example command? My guess it your browser has cached in the Service Worker.

**Comment by XsylenZ** [comment]
I cleared everything from the browser and it works now. 

My guess is indeed that I tried the example url's some sessions ago. I had a hard time just now to remove the cache.

Many thanks!

**Comment by tsvetlin** [comment]
Told you, there are no magic constants ;) 

(BTW the Management Tool 4.1.3 will be released in the following days)

**Comment by XsylenZ** [comment]
I'm looking forward to it, maybe I will change my project to the latest version then. 

The management tool is super convenient, good work! ;)
