### ISSUE TITLE
Management Tool 4.1.3

### ISSUE THREAD

**Issue by sumi0910** [arrowhead-f/mgmt-tool-js#5]
Used the below command 
**docker run -it -p 3000:5000 
--name arrowhead-react-container 
-e REACT_APP_ARROWHEAD_SR_URL=https://localhost:8443
-e REACT_APP_ARROWHEAD_AUTH_URL=https://localhost:8445
-e REACT_APP_ARROWHEAD_ORCH_URL=https://localhost:8441
-e REACT_APP_ARROWHEAD_GK_URL=https://localhost:8449
-e REACT_APP_ARROWHEAD_GW_URL=https://localhost:8453
-e REACT_APP_ARROWHEAD_EH_URL=https://localhost:8455
portus.arrowhead-ci.tmit.bme.hu/tools/management-tool**

But unable to save any data under Authorization and Gatekeeper tab in the management tool. 
Getting error " Saving is unsuccessful"

![image](https://user-images.githubusercontent.com/44111991/69816090-f8fac600-11f7-11ea-8dee-7bad699c7316.png)

Kudos to the successful event and great work!

**Comment by tsvetlin** [comment]
Hello!

Thanks :)

Could you please click on a request and show me the Headers and the Preview?

Svetlin

**Comment by sumi0910** [comment]
Sorry Svetlin, I don't know whether I get your question properly or not. I have provided the information to the best I can.

![image](https://user-images.githubusercontent.com/44111991/69863591-83e1cc00-129d-11ea-929f-bc9897cc43e9.png)

![image](https://user-images.githubusercontent.com/44111991/69863863-15513e00-129e-11ea-8ecb-25e1b5706add.png)

Thank you!

**Comment by sumi0910** [comment]
Hello,
Is there any update regarding it?

Thanks and regards,
Suman

**Comment by tsvetlin** [comment]
Hello! 

Could you please click on a request and show me the Headers and the Preview?

![image](https://user-images.githubusercontent.com/15650896/70059634-6be1b380-15e1-11ea-8ddd-5d3204474f5a.png)

**Comment by sumi0910** [comment]
Operating in insecure mode : 

![image](https://user-images.githubusercontent.com/44111991/70065499-86208f00-15eb-11ea-8247-1434c191c557.png)

**Comment by sumi0910** [comment]
Is there any update?

Thanks and regards,
Suman

**Comment by tsvetlin** [comment]
Hello!

Please provide a screenshot with information. Look at mine. It has HTTP status code, message . And please provide a screenshot from the response tab also.

Best wishes,
Svetlin

**Comment by sumi0910** [comment]
Hello,

I don't see any status code in the Header and there is no response data loaded under the response tab as shown in the below screenshots. Let me know what might have gone wrong.
![image](https://user-images.githubusercontent.com/44111991/70711513-0331bf80-1ce2-11ea-9258-6b480327b564.png)
![image](https://user-images.githubusercontent.com/44111991/70711545-16448f80-1ce2-11ea-8465-a0d602da527f.png)

Thanks and regards,
Suman

**Comment by tsvetlin** [comment]
The problem is, that you don't have a certificate / the proper certificate installed.

What operation system are you using?

You are trying to access the arrowhead.tmit.bme.hu Arrowhead cloud which requires a custom Sysop.p12.

Before you were trying to access Arrowhead running on localhost.

Which one would you like to access?

**Comment by sumi0910** [comment]
Operating System: Linux
I would like to access Arrowhead running on localhost.

**Comment by tsvetlin** [comment]
In your docker run command, which you linked first, you used localhost urls, but in the screenshot you were using the arrowhead.tmit.bme.hu url. This is the issue.

**Comment by sumi0910** [comment]
The issue is with the certificates. I need to figure out how to add certificates in chrome for Linux OS. Once I figure out that, I think the rest of the issue will be solved. Thanks for the help and support!
